language: emacs-lisp
sudo: required
services:
  - docker
script:
  - docker build -t quay.io/dtan4/dot.emacs.d .
notifications:
  slack:
    secure: tchbVC+BL/kmCblzgOlr8/GBRBVbakJx34uy5cmvarLmFiv4M+/m5OdpoKMun7CR5ezLJBLPR33UNTPAc8UzhjW3yK5xD3zMIleQXvdoDiyGb8ycu1gl+lmX78sh6ExhcNbFP3JzN/89XaiNeqX4izk5zIgaZMAGTY3sAOEZ1Xc=
