language: emacs-lisp
# https://github.com/travis-ci/travis-ci/issues/9073#issuecomment-358701996
sudo: required
env:
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
before_install:
  - make symlink
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION)
  - make -f emacs-travis.mk install_emacs
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
before_script:
  - ls -al ~/.emacs.d
script:
  - make integration-test
