language: emacs-lisp
env:
  matrix:
    - EMACS_VERSION=24.5
before_install:
  - sudo apt-get update -qq &&
    sudo apt-get build-dep -qq emacs &&
    sudo apt-get install -qq libmagickwand-dev libselinux1-dev libgnutls-dev texinfo cmigemo libmigemo-dev
  - wget -O /tmp/emacs-$EMACS_VERSION.tar.gz http://ftp.gnu.org/gnu/emacs/emacs-$EMACS_VERSION.tar.gz &&
    cd /tmp &&
    tar zxvf emacs-$EMACS_VERSION.tar.gz &&
    cd emacs-$EMACS_VERSION &&
    ./configure &&
    make &&
    make install
  - ln -s `pwd` ~/.emacs.d
  - emacs --version
script:
  travis_retry rake ci
notifications:
  slack:
    secure: tchbVC+BL/kmCblzgOlr8/GBRBVbakJx34uy5cmvarLmFiv4M+/m5OdpoKMun7CR5ezLJBLPR33UNTPAc8UzhjW3yK5xD3zMIleQXvdoDiyGb8ycu1gl+lmX78sh6ExhcNbFP3JzN/89XaiNeqX4izk5zIgaZMAGTY3sAOEZ1Xc=
