language: emacs-lisp
before_install:
  - BASE_DIR=`pwd`
    sudo apt-get update -qq &&
    sudo apt-get install build-essential &&
    sudo apt-get build-dep -qq emacs24 &&
    wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.gz -P /tmp &&
    cd /tmp &&
    tar -zxf emacs-24.4.tar.gz &&
    cd emacs-24.4 &&
    ./configure &&
    make &&
    sudo make install
  - ln -s `pwd` ~/.emacs.d
  - emacs --version
script:
  rake test
