language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq -y build-essential &&
    sudo apt-get build-dep -qq -y emacs24
  - wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.gz -P /tmp &&
    BASE_DIR=`pwd` &&
    cd /tmp &&
    tar -zxf emacs-24.4.tar.gz &&
    cd emacs-24.4 &&
    ./configure &&
    make &&
    sudo make install &&
    cd $BASE_DIR
  - ln -s `pwd` ~/.emacs.d
  - emacs --version
script:
  rake test
