(require 'ucs-normalize)
(setenv "LANG" "ja_JP.UTF-8")
(set-language-environment "Japanese")
;;  (set-language-environment 'utf-8)
(set-locale-environment nil)
(prefer-coding-system 'utf-8-unix)
(set-default-coding-systems 'utf-8-unix)
(setq file-name-coding-system 'utf-8-hfs)
(setq locale-coding-system 'utf-8-hfs)
(setq coding-system-for-write 'utf-8-unix)
