;; http://syohex.hatenablog.com/entry/2015/10/10/171926
;; (when (and (executable-find "cmigemo")
;;            (require 'migemo nil t))
;;   (setq migemo-options '("-q" "--emacs"))
;;   (setq migemo-command "cmigemo")
;;   (setq migemo-dictionary "/usr/share/cmigemo/utf-8/migemo-dict")
;;   (setq migemo-user-dictionary nil)
;;   (setq migemo-regex-dictionary nil)
;;   (setq migemo-coding-system 'utf-8-unix)
;;   (setq helm-use-migemo t)
;;   (load-library "migemo")
;;   (migemo-init)
;;   (helm-migemo-mode +1))
