name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: quay.io
            repository: quay.io/dtan4/emacs
            tag_with_ref: true
            # push: ${{ github.ref == "refs/heads/master" }}
